---
title:  "MODEL_COMPARISON_FIGURE5"
author: "Matthew J Shannon"
date:   "18/01/2024"
output: html_document
---

# Load in all dependencies

```{r, include = FALSE}
devtools::install_github ('chris-mcginnis-ucsf/DoubletFinder')
devtools::install_github ('satijalab/seurat-wrappers')
remotes::install_github  ("mojaveazure/seurat-disk")
devtools::install_github ("velocyto-team/velocyto.R")
BiocManager::install     ("pcaMethods")
BiocManager::install     ('MAST')
BiocManager::install     ('org.Hs.eg.db')
BiocManager::install     (version = "3.12")
BiocManager::install     ('Seurat')
BiocManager::install     ('readxl')
BiocManager::install     ('modes')
BiocManager::install     ('pheatmap')
BiocManager::install     ('limma')
BiocManager::install     ('clustree')
BiocManager::install     ('clusterProfiler')
BiocManager::install     ('EnhancedVolcano')
install.packages         ('fields')
install.packages         ('plotly')
install.packages         ("VennDiagram")
library                  (Seurat)
library                  (readr)
library                  (tidyverse)
library                  (Matrix)
library                  (dplyr)
library                  (ggplot2)
library                  (cowplot)
library                  (tibble)
library                  (readxl)
library                  (sctransform)
library                  (fields)
library                  (KernSmooth)
library                  (ROCR)
library                  (parallel)
library                  (reshape2)
library                  (pheatmap)
library                  (DoubletFinder)
library                  (limma)
library                  (SeuratWrappers)
library                  (SeuratDisk)
library                  (plotly)
library                  (clustree)
library                  (velocyto.R)
library                  (MAST)
library                  (EnhancedVolcano)
library                  (clusterProfiler)
library                  (AnnotationDbi)
library                  (org.Hs.eg.db)
library                  (VennDiagram)
library                  (RColorBrewer)
library                  (EnhancedVolcano)
library                  (xlsx)
gc                       ()
```

# Load the integrated and model-specific trophoblast Seurat objects

```{r}
# Integrated (all models) trophoblast object
load         (file = "~/Desktop/FINAL_Trophoblast_Data.Rdata")
DefaultAssay (Trophoblasts) <- "integrated"

# MPI (in vivo) trophoblast object
load         (file = "~/Desktop/MPI.Rdata")
DefaultAssay (MPI) <- "integrated"

# TBpOrg (in vitro) trophoblast object
load         (file = "~/Desktop/TBpOrg.Rdata")
DefaultAssay (TBpOrg) <- "integrated"

# TBsOrg (in vitro) trophoblast object
load         (file = "~/Desktop/TBsOrg.Rdata")
DefaultAssay (TBsOrg) <- "integrated"
```

# Figure 5

## Extravillous Differentiation Branch Comparison

```{r, Figure 5B, Integrated (in vivo + in vitro) extravillous differentiation branch subset}
Extravillous  <- subset (Trophoblasts, idents = c("TSC", "cCTB 1", "cCTB 2", "cCTB 3", "EVT"))
```

```{r, Figure 5B, Integrated (in vivo + in vitro) extravillous differentiation branch UMAP}
UMAPPlot (Extravillous, label = TRUE, pt.size = 3) + NoLegend ()
```

```{r, Figure 5C subset}
EVTs <- subset (Trophoblasts, idents = c("EVT"))
```

```{r, Figure 5C heatmap}
Idents (EVTs) <- EVTs@meta.data$Model
av.exp        <- AverageExpression (EVTs)$RNA
cor.exp       <- as.data.frame     (cor (av.exp))
cor.exp$x     <- rownames          (cor.exp)
cor.df        <- tidyr::gather     (data = cor.exp, y, correlation, c('MPI', 'TBpOrg', 'TBsOrg'))
cor.df

my_levels <- c("MPI", "TBpOrg", "TBsOrg")
cor.df$x  <- factor (cor.df$x, levels = my_levels)
cor.df$y  <- factor (cor.df$y, levels = my_levels)

ggplot               (cor.df, aes (x, y, fill = correlation)) +
geom_tile            () +
scale_fill_gradientn (limits = c(0, 1), colours = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100))
```

## Differential gene expression analysis

```{r, Figure 5E MPI vs TBpOrg differential gene expression analysis}
DefaultAssay (EVTs) <- "RNA"

TBpOrg.EVT.response <- FindMarkers (EVTs,
                                    ident.1         = c("MPI"),
                                    ident.2         = c("TBpOrg"),
                                    test.use        = "MAST",
                                    logfc.threshold = -Inf,
                                    min.pct         = -Inf,
                                    min.diff.pct    = -Inf,
                                    verbose         = FALSE)
                       head        (TBpOrg.EVT.response, n = 100)
```

```{r}
write.xlsx (TBpOrg.EVT.response, file = "MPI_TBpOrg_EVT_DGE.xlsx")
```

```{r, Figure 5E MPI vs TBpOrg volcano plot}
EnhancedVolcano (TBpOrg.EVT.response,
                 lab             = rownames (TBpOrg.EVT.response),
                 x               = "avg_log2FC",
                 y               = "p_val_adj",
                 FCcutoff        = 1.00,
                 pCutoff         = 10e-50,
                 pointSize       = 4.0,
                 col             = c('grey', 'grey', 'grey', 'red'),
                 colAlpha        = 1,
                 selectLab       = c('FOS', 'NPC2', 'GLRX', 'FN1', 'NOTUM', 'PAPPA2', '7SK.2', 'MBNL2', 'CLU', 'LGR4', 'TNNI2', 'PEG10', 'CDH5'), 
                 xlim            = c(-6, 6),
                 gridlines.major = FALSE,
                 drawConnectors  = TRUE, 
                 gridlines.minor = FALSE) + NoLegend () + ggtitle (NULL)
```

```{r, Figure 5E MPI vs TBsOrg differential gene expression analysis}
DefaultAssay (EVTs) <- "RNA"

TBsOrg.EVT.response <- FindMarkers (EVTs,
                                    ident.1         = c("MPI"),
                                    ident.2         = c("TBsOrg"),
                                    test.use        = "MAST",
                                    logfc.threshold = -Inf,
                                    min.pct         = -Inf,
                                    min.diff.pct    = -Inf,
                                    verbose         = FALSE)
                       head        (TBsOrg.EVT.response, n = 100)
```

```{r}
write.xlsx (TBsOrg.EVT.response, file = "MPI_TBsOrg_EVT_DGE.xlsx")
```

```{r, Figure 5E MPI vs TBsOrg volcano plot}
EnhancedVolcano (TBsOrg.EVT.response,
                 lab             = rownames (TBsOrg.EVT.response),
                 x               = "avg_log2FC",
                 y               = "p_val_adj",
                 FCcutoff        = 1.00,
                 pCutoff         = 10e-50,
                 pointSize       = 4.0,
                 col             = c('grey', 'grey', 'grey', 'red'),
                 colAlpha        = 1,
                 selectLab       = c('FN1', 'IGFBP3', 'NPC2', 'FOS', 'ADM', 'TGFB1', 'LAIR2', 'PAPPA2', 'DUSP5', 'HTRA4', 'PSG5', 'TKT', 'CGB', 'IFI27', 'CGA', 'CSH1'),
                 xlim            = c(-6, 6),
                 gridlines.major = FALSE,
                 drawConnectors  = TRUE, 
                 gridlines.minor = FALSE) + NoLegend () + ggtitle (NULL)
```

## Extravillous differentiation branch regulon transcription factor dot plots

```{r, Figure 5F}
# Plotting transcription factors identified in Table S7
Idents  (EVTs) <- EVTs@meta.data$Model
DotPlot (EVTs,
         features  = c("SRF",
                       "MXI1",
                       "KLF6",
                       "SOX4",
                       "TCF7L2",
                       "BATF3",
                       "ASCL2",
                       "XRCC4",
                       "SNAI1",
                       "MXD4",
                       "MYCN",
                       "FOS",
                       "THRB",
                       "FOSL2",
                       "ELF4",
                       "GTF3A"),
         assay     = "RNA",
         cols      = c("lightgrey", "red"),
         col.min   = 0,
         col.max   = 1,
         dot.min   = 0,
         dot.scale = 15)
```

```{r, Figure 5G}
       Idents (TBpOrg)  <- "assignment"
TBpOrg$assignment.state <- paste  (Idents (TBpOrg), TBpOrg$State, sep = "_")
TBpOrg$assignment       <- Idents (TBpOrg)

       Idents (TBpOrg)  <- "assignment.state"
table (Idents (TBpOrg))
```

```{r, Figure 5G TBpOrg UMAPs}
UMAPPlot (TBpOrg,
          label    = TRUE,
          pt.size  = 3,
          split.by = "State",
          cols     = c('CTB'  = 'darkorange1',
                       'TSC'  = '#A65628',
                       'cCTB' = 'red3',
                       'EVT'  = 'forestgreen',
                       'SCTp' = 'dodgerblue4')) + NoLegend ()
```

```{r, Figure 5G TBpOrg Barplots}
my_levels <- c("0_Undifferentiated",  "0_Differentiated",
               "1_Undifferentiated",  "1_Differentiated",
               "2_Undifferentiated",  "2_Differentiated" )

TBpOrg$assignment.state <- factor (TBpOrg$assignment.state, levels = my_levels)

ggplot             (TBpOrg@meta.data, aes (x = c(TBpOrg$assignment.state), fill = TBpOrg$cellbin)) +
theme_classic2     () +
geom_bar           (position     = "fill") +
scale_y_continuous (labels       = scales::percent) +
theme              (text         = element_text (size   = 35)) +
theme              (axis.text    = element_text (size   = 35)) +
theme              (axis.title.x = element_text (face   = "bold")) +
theme              (axis.title.y = element_text (face   = "bold")) +
theme              (legend.text  = element_text (size   = 15)) +
theme              (axis.text.y  = element_text (angle  = 90)) +
theme              (axis.text.x  = element_text (angle  = 90)) +
theme              (axis.text.y  = element_text (hjust  = 0.5)) +
theme              (axis.text.x  = element_text (colour = "black")) +
theme              (axis.text.y  = element_text (colour = "black")) +
xlab               ("Trophoblast Model") +
ylab               ("Cell Proportion")
```

```{r, Figure 5G}
       Idents (TBsOrg)  <- "orig.ident"
TBsOrg$assignment.state <- paste  (Idents (TBsOrg), TBsOrg$State, sep = "_")
TBsOrg$assignment       <- Idents (TBsOrg)

       Idents (TBsOrg)  <- "assignment.state"
table (Idents (TBsOrg))
```

```{r, Figure 5G TBsOrg UMAPs}
UMAPPlot (TBsOrg,
          label    = TRUE,
          pt.size  = 3,
          split.by = "State",
          cols     = c('CTB'  = 'darkorange1',
                       'TSC'  = '#A65628',
                       'cCTB' = 'red3',
                       'EVT'  = 'forestgreen',
                       'SCTp' = 'dodgerblue4')) + NoLegend ()
```

```{r, Figure 5G TBsOrg Barplots}
my_levels <- c("CT27_Undifferentiated",  "CT27_Differentiated",
               "CT29_Undifferentiated",  "CT29_Differentiated",
               "CT30_Undifferentiated",  "CT30_Differentiated" )

my_cells  <- c("TSC",  "CTB", "cCTB",  "EVT", "SCTp")

TBsOrg$assignment.state <- factor (TBsOrg$assignment.state, levels = my_levels)
TBsOrg$celltype         <- factor (TBsOrg$celltype, levels = my_cells)

ggplot             (TBsOrg@meta.data, aes (x = c(TBsOrg$assignment.state), fill = TBsOrg$celltype)) +
theme_classic2     () +
geom_bar           (position     = "fill") +
scale_y_continuous (labels       = scales::percent) +
theme              (text         = element_text (size   = 35)) +
theme              (axis.text    = element_text (size   = 35)) +
theme              (axis.title.x = element_text (face   = "bold")) +
theme              (axis.title.y = element_text (face   = "bold")) +
theme              (legend.text  = element_text (size   = 15)) +
theme              (axis.text.y  = element_text (angle  = 90)) +
theme              (axis.text.x  = element_text (angle  = 90)) +
theme              (axis.text.y  = element_text (hjust  = 0.5)) +
theme              (axis.text.x  = element_text (colour = "black")) +
theme              (axis.text.y  = element_text (colour = "black")) +
xlab               ("Trophoblast Model") +
ylab               ("Cell Proportion")
```

# Supplemental Figure 5

```{r, Supplemental figure 5A subset}
cCTBs <- subset (Trophoblasts, idents = c("cCTB"))
```

```{r, Supplemental figure 5A heatmap}
Idents (cCTBs) <- cCTBs@meta.data$Model
av.exp         <- AverageExpression (cCTBs)$RNA
cor.exp        <- as.data.frame     (cor (av.exp))
cor.exp$x      <- rownames          (cor.exp)
cor.df         <- tidyr::gather     (data = cor.exp, y, correlation, c('MPI', 'TBpOrg', 'TBsOrg'))
cor.df

my_levels <- c("MPI", "TBpOrg", "TBsOrg")
cor.df$x  <- factor (cor.df$x, levels = my_levels)
cor.df$y  <- factor (cor.df$y, levels = my_levels)

ggplot               (cor.df, aes (x, y, fill = correlation)) +
geom_tile            () +
scale_fill_gradientn (limits = c(0, 1), colours = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu"))) (100))
```

```{r, Supplemental figure 5C renaming cluster idents}
Trophoblasts <- RenameIdents (Trophoblasts,
                              'CTB 1'  = "CTB",
                              'CTB 2'  = "CTB",
                              'CTB 3'  = "CTB",
                              'CTB 4'  = "CTB",
                              'TSC'    = "TSC",
                              'cCTB 1' = "cCTB",
                              'cCTB 2' = "cCTB",
                              'cCTB 3' = "cCTB",
                              'EVT'    = "EVT",
                              'SCTp 1' = "SCTp",
                              'SCTp 2' = "SCTp")

Trophoblasts$celltype <- Idents (Trophoblasts)
```

```{r, Supplemental figure 5C idents}
Trophoblasts$celltype.model  <- paste       (Idents (Trophoblasts), Trophoblasts$Model, sep = "_")
Trophoblasts$celltype        <- Idents      (Trophoblasts)

       Idents (Trophoblasts) <- "celltype.model"

# Table S5A
table (Idents (Trophoblasts))
```

```{r, Supplemental figure 5C dotplot}
DefaultAssay (Trophoblasts) <- "RNA"
Idents       (Trophoblasts) <- "celltype.model"

my_levels <- c("CTB_MPI",  "CTB_TBpOrg",  "CTB_TBsOrg",
               "TSC_MPI",  "TSC_TBpOrg",  "TSC_TBsOrg",
               "cCTB_MPI", "cCTB_TBpOrg", "cCTB_TBsOrg",
               "EVT_MPI",  "EVT_TBpOrg",  "EVT_TBsOrg",
               "SCTp_MPI", "SCTp_TBpOrg", "SCTp_TBsOrg")

Trophoblasts@active.ident <- factor (Trophoblasts@active.ident, levels = my_levels)

DotPlot (Trophoblasts,
         features  = c("HLA-A",
                       "HLA-B",
                       "HLA-C",
                       "HLA-E",
                       "HLA-F",
                       "HLA-G"),
         assay     = "RNA",
         cols      = c("lightgrey", "red"),
         col.min   = 0,
         col.max   = 1,
         dot.min   = 0,
         dot.scale = 15)
```
